apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    name: hello-world
  type: NodePort
